name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Python quality and format checker
      # You may pin to the exact commit or the version.
      # uses: konstruktoid/action-pylint@c2bd422ba2465db9dfd5731f984164dcf961089d
      uses: konstruktoid/action-pylint@v0.0.7
    
    - name: Python Safety Check
      # You may pin to the exact commit or the version.
      # uses: aufdenpunkt/python-safety-check@d5468d88a766a647545a256f118b216833f91088
      uses: aufdenpunkt/python-safety-check@v1.0.5
      with:
        # Optional Safety script parameters. (e.g. --ignore=1234 or -i 1234)
        # safety_args: # optional, default is 
        # Set true to scan required python packages without installing them.
        scan_requirements_file_only: false
        
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test
